version: '3.9'

services:
  nginx: 
    image: nginx:1.21.6-alpine
    depends_on:
      - temperature-service
      - precipitation-service
      - weather-app
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - weather-network

  temperature-service: 
    image: temperature-service
    container_name: temperature-service
    build: ./temperature-service
    ports:
      - 3333:3333
    restart: on-failure
    networks: 
      - weather-network

  precipitation-service: 
    image: precipitation-service
    container_name: precipitation-service
    build: ./precipitation-service
    ports:
      - 3334:3334
    restart: on-failure
    networks: 
      - weather-network

  weather-app: 
    image: weather-app
    container_name: weather-app
    build: ./weather-app
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - temperature-service
      - precipitation-service
    networks: 
      - weather-network

networks:
  weather-network:
    driver: bridge
